name: bidder
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluttermoji: ^1.0.2
  firebase_core: ^2.29.0
  get: ^4.6.6
  carousel_slider: ^4.2.1
  get_it: ^7.6.7
  cloud_firestore: ^4.16.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  
